# Generated by Django 2.2.2 on 2020-02-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20180920_1245'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE translations_translation MODIFY COLUMN text longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL;")
    ]
